import React from "react";
import NavBar from "@/components/navbar/NavBar";
import "./styles/globals.css";
import Container from "../../components/Container";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// DARKMODE TODO
// jelenlegi mode localStorage
// gomb
// Server vs Client side component -> hogy lehet elérni hogy a client side már adatokkal rendelődjön
//    (useEffect nélkül kérjük le az adatokat.)

// TODO
// https://nextui.org/blog/nextui-v2

export default async function RootLayout(props : any) {
  const NavBarComponent : JSX.Element = await NavBar({currentLanguage: props.params.lang});

  return (
    <Container lang={props.params.lang}>
        {NavBarComponent}
        {props.children}
    </Container>
      
  )
}
