import React from "react";
import NavBar from "@/components/navbar/NavBar";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout(props : any) {
  const NavBarComponent : JSX.Element = await NavBar({currentLanguage: props.params.lang});

  return (
    <html lang={props.params.lang}>
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossOrigin="anonymous" />
      </head>
      <body>
        {NavBarComponent}

        {props.children}
      </body>
    </html>
  )
}
